apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: hello
type: Opaque
stringData:
  MYSQL_HOST: mysql.database.svc.cluster.local
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: hello_db
  MYSQL_USER: hello_user
  MYSQL_PASSWORD: hello_password_123
