---
- name: Deploy MySQL
  ansible.builtin.shell: |
    kubectl apply -f {{ project_root_remote }}/kubernetes/mysql/secret.yaml
    kubectl apply -f {{ project_root_remote }}/kubernetes/mysql/service.yaml
    kubectl apply -f {{ project_root_remote }}/kubernetes/mysql/statefulset.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: true

- name: Wait for MySQL rollout
  ansible.builtin.shell: kubectl -n {{ database_namespace }} rollout status statefulset/mysql --timeout=600s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false
