apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password_123
  MYSQL_DATABASE: hello_db
  MYSQL_USER: hello_user
  MYSQL_PASSWORD: hello_password_123
